export const he = {
  brand: 'ניהול בית ספר',
  homeLead: 'יש לפתוח את הפורטל ממכשיר מנוהל, או להיכנס לממשק הניהול.',
  openAdmin: 'ממשק ניהול',
  openApiDocs: 'מסמכי API ו־Webhooks',
  portalTitle: 'פורטל תלמיד',
  portalLead: 'בקשת עזרה, עדכונים, וחנות האפליקציות של בית הספר.',
  portalStoreTitle: 'חנות אפליקציות',
  portalStoreLead: 'אפליקציות מותרות להתקנה, וחיפוש לבקשת גישה.',
  portalTabStore: 'חנות',
  portalTabRequest: 'בקשה',
  portalTabUpdates: 'עדכונים',
  storeLead: 'חפשו אפליקציות. מותרות — אפשר להתקין מחנות האפליקציות. אחרות — בקשו גישה.',
  storeAllowed: 'מותרות עבורכם',
  storeSearch: 'חיפוש אפליקציות',
  storeInstall: 'התקנה',
  storeInstallViaChrome: 'פותח ב-Chrome להתקנה (בלי חנות האפליקציות)…',
  storeRequestAccess: 'בקשת גישה',
  storePending: 'ממתין לאישור',
  storeEmptyAllowed: 'אין עדיין אפליקציות מותרות מעבר לבסיס המערכת.',
  storeOpenUpdates: 'לעדכונים',
  updatesLead: 'סטטוס הבקשות והודעות מהניהול. רעננו את המסך או פתחו שוב את הקיצור כדי לראות שינויים.',
  updatesBadgeNew: 'חדש',
  device: 'מכשיר',
  category: 'סוג הבקשה',
  catUrl: 'אתר',
  catApp: 'אפליקציה',
  catGeneral: 'כללי',
  catBug: 'תקלה',
  url: 'כתובת האתר',
  urlWillSave: 'יישמר כ',
  searchApp: 'חיפוש ב-App Store',
  search: 'חיפוש',
  searching: 'מחפש…',
  searchMinChars: 'הקלידו לפחות שני תווים',
  searchFailed: 'החיפוש נכשל',
  searchDevices: 'חיפוש מכשיר…',
  searchGroups: 'חיפוש קבוצה…',
  searchPacks: 'חיפוש חבילה…',
  searchProfiles: 'חיפוש פרופיל…',
  noApps: 'לא נמצאו אפליקציות.',
  noMatches: 'אין תוצאות לחיפוש.',
  pick: 'בחירה',
  selectedApp: 'אפליקציה שנבחרה',
  change: 'החלפה',
  subject: 'נושא',
  bugTitle: 'כותרת התקלה',
  reasonUrl: 'למה צריך את זה?',
  reasonApp: 'למה צריך את האפליקציה?',
  reasonBug: 'מה קרה? (שלבי שחזור)',
  reasonGeneral: 'פרטים',
  submit: 'שליחה',
  sending: 'שולח…',
  alreadyAllowed: 'כבר ברשימת המותרים',
  alreadyAllowedHint: 'כבר מאושר במכשיר — אין צורך לבקש שוב.',
  pendingRequest: 'בקשה פתוחה',
  deniedBefore: 'נדחה בעבר — אפשר לבקש שוב',
  checkStatus: 'בודק הרשאות…',
  myRequests: 'הבקשות שלי',
  noRequests: 'עדיין אין בקשות.',
  sentOk: 'הבקשה נשלחה',
  openThread: 'פתיחת שיחה',
  conversation: 'שיחה',
  reply: 'תשובה',
  replyPlaceholder: 'כתבו תשובה…',
  replyPlaceholderAdmin: 'הוסיפו הערה לתלמיד…',
  sendReply: 'שליחה',
  pickRequest: 'בחרו בקשה מהרשימה',
  lastMsg: 'אחרון',
  queue: 'תור בקשות',
  ticket: 'בקשה נבחרת',
  you: 'אתם',
  adminRole: 'ניהול',
  studentRole: 'תלמיד',
  noMessages: 'אין הודעות עדיין.',
  reopenHint: 'תשובה שלכם תפתח מחדש את הבקשה אצל הניהול.',
  adminReplied: 'תשובה מהניהול',
  waitingYourReply: 'צריך תשובה',
  waitingStudent: 'ממתין לתלמיד',
  waitingAdmin: 'ממתין לניהול',
  closedTicket: 'סגור',
  nextAction: 'מצב',
  lastFromAdmin: 'מהניהול',
  lastFromYou: 'מאתכם',
  lastFromStudent: 'מהתלמיד',
  admin: 'ניהול',
  adminLead: 'בקשות, שיחות ורשימות מותרים.',
  tabRequests: 'בקשות',
  tabGroups: 'קבוצות',
  tabAllow: 'רשימות מותרים',
  tabAllowShort: 'מותרים',
  tabDevices: 'מכשירים',
  tabCredits: 'קרדיטים',
  tabLogs: 'לוגים',
  tabEnrollment: 'הרשמה',
  tabSettings: 'הגדרות',
  systemAppsTitle: 'אפליקציות מערכת של אפל',
  systemAppsLead:
    'שירותים ואפליקציות מובנות של iOS. הן מופעלות אוטומטית לכל מכשיר ומוסתרות מהרשימות הגדולות.',
  systemAppsEnabled: 'פעיל לכולם',
  systemAppsDisabled: 'כבוי',
  systemAppsCount: '{n} פריטים',
  systemAppsSearchHint: 'חפשו שם או מזהה כדי להציג פריט מהרשימה.',
  tabMdm: 'MDM',
  activityLead: 'יומן פעולות של ניהול המכשירים — סינון לפי זמן, סוג, מכשיר ותוצאה.',
  activityWhen: 'מתי',
  activityCategory: 'קטגוריה',
  activityAction: 'פעולה',
  activityActor: 'מבצע',
  activityResult: 'תוצאה',
  activitySummary: 'תיאור',
  activitySearch: 'חיפוש בתיאור',
  activityEmpty: 'אין לוגים להצגה',
  activityDetail: 'פרטי אירוע',
  activityPrev: 'הקודם',
  activityNext: 'הבא',
  activityRequestId: 'מזהה בקשה',
  activityCommandId: 'מזהה פקודה',
  activityCatMdm: 'ניהול מכשיר',
  activityCatPolicy: 'הרשאות',
  activityCatGroups: 'קבוצות',
  activityCatRequests: 'בקשות',
  activityCatCredits: 'קרדיטים',
  activityCatDevices: 'מכשירים',
  activityCatAbm: 'ABM',
  activityCatSystem: 'מערכת',
  activityResultOk: 'הצלחה',
  activityResultError: 'שגיאה',
  activityResultInfo: 'מידע',
  activityActorAdmin: 'ניהול',
  activityActorDevice: 'מכשיר',
  activityActorSystem: 'מערכת',
  activityActorWebhook: 'Webhook',
  allowAll: 'הכל מותר',
  allowAllHint: 'מסיר את מגבלות בית הספר. כיבוי מחזיר את המכשיר לכללי הקבוצה הנוכחיים.',
  openDevice: 'דף מכשיר',
  quickActions: 'פעולות מהירות',
  openDevicePage: 'לדף המכשיר',
  backToDevices: 'חזרה למכשירים',
  deviceNotFound: 'המכשיר לא נמצא',
  deviceStatus: 'מצב המכשיר',
  refreshStatus: 'רענון',
  statusNeedsMdm: 'סטטוס זמין רק כשהמכשיר מחובר לניהול בית הספר.',
  statusEmpty: 'אין נתונים עדיין — לחצו רענון.',
  battery: 'סוללה',
  model: 'דגם',
  osVersion: 'מערכת',
  storage: 'אחסון',
  serial: 'מספר סידורי',
  groups: 'קבוצות',
  managed: 'מחובר לניהול',
  notManaged: 'לא מחובר לניהול',
  lastSeen: 'נראה לאחרונה',
  deviceAllowEdit: 'הרשאות למכשיר זה',
  deviceAllowEditHint: 'הוספה והסרה כאן חלות רק על המכשיר. מה שמותר בפועל כולל גם קבוצות וחבילות.',
  openWhitelistsForDevice: 'פתיחה ברשימת המותרים',
  openPack: 'ניהול חבילה',
  effectivePolicy: 'מה מותר בפועל',
  lockDevice: 'נעילת מסך',
  lockConfirm: 'לנעול את המכשיר עכשיו?',
  clearPasscode: 'איפוס קוד גישה',
  clearPasscodeConfirm: 'לאפס את קוד הגישה במכשיר?',
  restartDevice: 'הפעלה מחדש',
  restartConfirm: 'להפעיל מחדש את המכשיר?',
  shutDownDevice: 'כיבוי',
  shutDownConfirm: 'לכבות את המכשיר?',
  eraseDevice: 'מחיקת מכשיר',
  eraseConfirm: 'פעולה בלתי הפיכה — המכשיר יימחק לחלוטין.',
  eraseTypeHint: 'הקלידו ERASE לאישור',
  lostMode: 'מצב אבוד',
  enableLostMode: 'הפעלת מצב אבוד',
  disableLostMode: 'כיבוי מצב אבוד',
  playLostSound: 'צליל איתור',
  locateDevice: 'איתור מיקום',
  lostModeMessage: 'הודעה על המסך',
  lostModePhone: 'טלפון ליצירת קשר (אופציונלי)',
  deviceActions: 'פעולות מכשיר',
  deviceInfoSection: 'מידע',
  securityInfo: 'מידע אבטחה',
  profileList: 'פרופילים מותקנים',
  installedApps: 'אפליקציות מותקנות',
  bulkSelected: 'נבחרו',
  bulkAllowAll: 'הכל מותר',
  bulkRestrict: 'הגבלה',
  bulkLock: 'נעילה',
  bulkRestart: 'הפעלה מחדש',
  bulkClearPasscode: 'איפוס קוד',
  bulkAddGroup: 'הוספה לקבוצה',
  whitelistApps: 'אפליקציות',
  whitelistWeb: 'אתרים',
  pasteUrlsHint: 'הדביקו כתובות (שורה לכל אתר) ולחצו הוספה',
  packsTab: 'חבילות מותרים',
  oneOffsTab: 'פריטים בודדים',
  packsLead: 'חבילות כמו «משחקים» — אוסף אפליקציות/אתרים שאפשר לשייך לקבוצות מכשירים או למכשיר בודד.',
  createPack: 'חבילה חדשה',
  packName: 'שם החבילה',
  packAssign: 'שיוך',
  packItems: 'תוכן החבילה',
  packItemsLead: 'בחבילה «{name}»: חפשו ב-App Store והוסיפו אפליקציות, או הוסיפו אתרים. אחר כך שייכו לקבוצה או למכשיר.',
  packSearchStore: 'חיפוש אפליקציה ב-App Store…',
  packSearchHint: 'הקלידו שם אפליקציה (לפחות שני תווים) ובחרו להוספה לחבילה.',
  packAddApp: 'הוספה לחבילה',
  packAddUrl: 'הוספת אתר',
  packInPack: 'כבר בחבילה',
  packAppsInPack: 'אפליקציות בחבילה',
  packUrlsInPack: 'אתרים בחבילה',
  packEmptyApps: 'עדיין אין אפליקציות בחבילה — חפשו למעלה ב-App Store.',
  packEmptyUrls: 'עדיין אין אתרים בחבילה — הוסיפו כתובת למעלה.',
  packAssignLead: 'למי החבילה חלה. בלי שיוך היא לא משפיעה על מכשירים.',
  packAssignEmpty: 'עדיין לא משויך.',
  packAssignedTo: 'משויך ל',
  emptyPacks: 'אין חבילות עדיין — צרו «משחקים» או דומה.',
  emptyProfiles: 'אין פרופילים עדיין — העלו קובץ .mobileconfig.',
  emptyGroups: 'אין קבוצות עדיין.',

  profilesTab: 'פרופילים',
  profilesLead:
    'פרופיל הגדרות של Apple (.mobileconfig) — Wi-Fi, הגבלות, VPN ועוד. מעלים קובץ, ואז משייכים לקבוצה או למכשיר. אפשר גם להוסיף או להסיר בטיימר.',
  profileUpload: 'העלאת פרופיל',
  profileUploadHint: 'קבצי .mobileconfig או .plist. הפרופיל מותקן במכשירים אחרי שיוך.',
  profileName: 'שם הפרופיל',
  profileDescription: 'תיאור',
  profileFile: 'קובץ הפרופיל',
  profileIdentifier: 'מזהה (PayloadIdentifier)',
  profileDownload: 'הורדת הקובץ',
  profileReplace: 'החלפת הקובץ',
  profileReplaced: 'קובץ הפרופיל הוחלף',
  profileDeleteConfirm: 'למחוק את הפרופיל? הוא יוסר מהמכשירים המשויכים.',
  profileItemsLead:
    'בפרופיל «{name}»: אפשר לשנות שם, להחליף את הקובץ, ולשייך לקבוצות או למכשירים.',
  profileAssignLead: 'למי הפרופיל מותקן. בלי שיוך הוא לא נדחף למכשירים.',
  profileOnDevice: 'פרופילים מותאמים',
  profileOnDeviceEmpty: 'אין פרופיל מותאם שמשויך למכשיר הזה.',
  profileOnDeviceHint: 'פרופילי .mobileconfig ששויכו למכשיר, לקבוצה שלו, או לכולם.',
  openProfile: 'ניהול פרופיל',

  timersTab: 'טיימרים',
  timersLead:
    'טיימר מוסיף או מסיר חבילות מותרים ופרופילים מותאמים ממכשירים או מקבוצות בזמן קבוע. השעות לפי שעון ישראל.',
  createTimer: 'טיימר חדש',
  timerName: 'שם הטיימר',
  timerAction: 'פעולה',
  timerActionAdd: 'הוספה',
  timerActionRemove: 'הסרה',
  timerPacks: 'חבילות',
  timerProfiles: 'פרופילים',
  timerDevices: 'מכשירים',
  timerGroups: 'קבוצות',
  timerSchedule: 'מתי',
  timerOnce: 'פעם אחת',
  timerWeekly: 'כל שבוע',
  timerRunAt: 'תאריך ושעה',
  timerTimeOfDay: 'שעה',
  timerWeekdays: 'ימי השבוע',
  timerDays: ['ראשון', 'שני', 'שלישי', 'רביעי', 'חמישי', 'שישי', 'שבת'],
  timerEnabled: 'פעיל',
  timerDisabled: 'כבוי',
  timerRunNow: 'הרצה עכשיו',
  timerNextRun: 'הרצה הבאה',
  timerLastRun: 'הרצה אחרונה',
  timerOverdue: 'ממתין להרצה',
  timerDone: 'הושלם',
  timerEmpty: 'אין טיימרים עדיין — צרו טיימר שמוסיף או מסיר חבילה או פרופיל בזמן קבוע.',
  timerNeedPacks: 'בחרו לפחות חבילה אחת או פרופיל אחד',
  timerNeedTargets: 'בחרו מכשיר או קבוצה',
  timerNeedWhen: 'בחרו מתי להריץ',
  timerNeedWeekdays: 'בחרו לפחות יום אחד',
  timerTzNote: 'השעות לפי שעון ישראל.',
  timerDeleteConfirm: 'למחוק את הטיימר?',
  timerSaved: 'הטיימר נשמר',
  timerDeleted: 'הטיימר נמחק',
  timerRan: 'הטיימר הורץ',
  timerEdit: 'עריכת טיימר',

  abmTitle: 'הרשמה אוטומטית (ABM / DEP)',
  abmLead:
    'כאן מחברים את Apple School Manager / Business Manager לשרת, כדי שמכשירים חדשים ייכנסו אוטומטית לניהול בית הספר אחרי איפוס.',
  abmStep1Title: '1. הורדת מפתח ציבורי מהשרת',
  abmStep1Body:
    'הורידו את קובץ ה־PEM מהכפתור למטה. תעלו אותו ב־Apple School/Business Manager כשיוצרים שרת MDM.',
  abmStep2Title: '2. יצירת שרת MDM ב־Apple',
  abmStep2Body:
    'היכנסו לפורטל של Apple → הגדרות → שרתי ניהול מכשירים → הוספת שרת MDM. העלו את ה־PEM, שמרו, והורידו את קובץ ה־Token (.p7m).',
  abmStep3Title: '3. העלאת ה־Token לשרת הזה',
  abmStep3Body:
    'העלו כאן את קובץ ה־Token שהורדתם מ־Apple. התוקף בדרך כלל לשנה — לפני שפג, הורידו Token חדש והעלו שוב.',
  abmStep4Title: '4. פרופיל הרשמה וסנכרון',
  abmStep4Body:
    'הגדירו פרופיל הרשמה פעם אחת. אחר כך לחצו סנכרון — הרשימה מתעדכנת מ־Apple, וכל מכשיר בלי הפרופיל מקבל אותו אוטומטית.',
  abmLinksTitle: 'קישורים שימושיים',
  abmLinkSchool: 'Apple School Manager',
  abmLinkBusiness: 'Apple Business Manager',
  abmLinkAsmMdm: 'מדריך Apple: חיבור שרת MDM (School)',
  abmLinkAbmMdm: 'מדריך Apple: חיבור שרת MDM (Business)',
  abmLinkAde: 'מדריך Apple: Automated Device Enrollment',
  abmDownloadCert: 'הורדת מפתח ציבורי (PEM)',
  abmUploadToken: 'העלאת Token מ־Apple',
  abmUploadTokenOk: 'ה־Token הועלה בהצלחה',
  abmUploadTokenHint: 'בחרו קובץ .p7m / Token שהורדתם מ־Apple',
  abmDepName: 'שם DEP בשרת',
  abmDepNameHint:
    'השם נשמר במסד הנתונים (לא ב־.env). אפשר לערוך לפני חיבור ל־Apple. אחרי העלאת Token עדיף לא לשנות — אחרת תצטרכו להעלות Token מחדש לשם החדש.',
  abmDepNameSave: 'שמירת שם DEP',
  abmDepNameSaved: 'שם DEP נשמר',
  companionTitle: 'אפליקציית KFilter במכשיר',
  companionLead:
    'השרת יכול להתקין את אפליקציית התלמיד (KFilter) דרך MDM, עם מזהה מכשיר אוטומטי (Managed App Config). עד ש־Custom App מופיע ב־ASM — הזינו את ה־Adam/iTunes ID.',
  companionItunesId: 'מזהה App Store (Adam / iTunes ID)',
  companionBundleId: 'Bundle ID',
  companionEnabled: 'התקנה אוטומטית בסנכרון מכשיר',
  companionSave: 'שמירת הגדרות KFilter',
  companionSaved: 'הגדרות KFilter נשמרו',
  companionPush: 'דחיפת KFilter למכשיר',
  companionPushOk: 'התקנת KFilter נשלחה למכשיר',
  companionConfig: 'שליחת מזהה מכשיר לאפליקציה',
  companionConfigOk: 'הגדרת KFilter נשלחה (Managed App Config)',
  companionHasPush: 'יש Push Token באפליקציה',
  companionNoPush: 'אין Push Token עדיין',
  vppTokenTitle: 'Apps & Books (VPP) — Content Token',
  vppTokenHint: 'העלו Token מ־Apple School/Business Manager (Payments and Billing → Apps and Books) כדי לשייך רישיון לפני התקנה.',
  vppTokenUpload: 'העלאת Content Token',
  vppTokenUploaded: 'ה־Token נשמר',
  vppTokenClear: 'מחיקת Token',
  vppTokenPresent: 'Token קיים',
  vppTokenMissing: 'אין Token',
  lockScreenTitle: 'הודעת מסך נעילה',
  lockScreenLead:
    'במכשירים מנוהלים (Supervised) מוצגים בתחתית מסך הנעילה שם המכשיר (כינוי) והערת בית ספר קבועה. שינוי ההערה נדחף לכל המכשירים.',
  lockScreenEnabled: 'הצג הודעה במסך נעילה',
  lockScreenFootnote: 'הערת בית ספר (שורה תחתונה)',
  lockScreenFootnoteHint: 'לדוגמה: מכשיר בית ספר · KFilter',
  lockScreenSave: 'שמירת הודעת נעילה',
  lockScreenSaved: 'הודעת הנעילה נשמרה (נדחף למכשירים)',
  abmActionsTitle: 'פעולות אחרי החיבור',
  abmSync: 'סנכרון מ־Apple',
  abmSyncHint: 'מושך את רשימת המכשירים מ־Apple, ומשבץ את פרופיל ההרשמה לכל מכשיר שעדיין בלי הפרופיל.',
  abmSyncAssigned: 'סונכרנו {n} מכשירים · שויך פרופיל ל־{m}',
  abmSyncNoneAssigned: 'סונכרנו {n} מכשירים · כולם כבר עם פרופיל הרשמה',
  abmDefineProfile: 'הגדרת פרופיל הרשמה',
  abmDefineProfileHint: 'יוצר פרופיל ADE ב־Apple עם כתובת ההרשמה, ומדלג על מסכי ההתקנה (שחזור ממכשיר אחר, Apple ID, תנאים, סיסמה וכו׳). נשארים Wi‑Fi, אישור MDM ומסך ברוכים הבאים.',
  abmAssignNeedProfile: 'קודם צרו פרופיל הרשמה.',
  abmProfileUuid: 'מזהה פרופיל הרשמה',
  abmProfileReady: 'פרופיל הרשמה פעיל',
  abmAfterAssign: 'אחרי הסנכרון, אפסו את המכשיר. בהתקנה: Wi‑Fi, אישור MDM, ומסך ברוכים הבאים — בלי שחזור ממכשיר אחר ובלי שאר מסכי ההסכמה.',
  abmNotConnected: 'אין Token פעיל מול Apple — השלימו את שלבים 1–3 למעלה.',
  abmConnected: 'מחובר ל־Apple (DEP)',
  abmConfiguredOnly: 'שם DEP מוגדר בשרת, אבל עדיין אין חיבור חי ל־Apple',
  abmAccountTitle: 'חשבון Apple',
  abmAccountOrg: 'ארגון',
  abmAccountServer: 'שם שרת MDM ב־Apple',
  abmAccountAdmin: 'מנהל Token',
  abmAccountEmail: 'אימייל ארגון',
  abmAccountPhone: 'טלפון',
  abmAccountType: 'סוג ארגון',
  abmAccountTypeEdu: 'חינוך (School Manager)',
  abmAccountTypeOrg: 'ארגון (Business Manager)',
  abmDevicesTitle: 'מכשירים משויכים ב־Apple',
  abmDevicesEmpty: 'אין מכשירים משויכים לשרת הזה ב־Apple — שייכו בפורטל Apple או אחרי סנכרון.',
  abmDevicesCount: 'מכשירים',
  abmDevicesLastSync: 'סנכרון אחרון',
  abmDevicesLoadingCache: 'טוען מכשירים שמורים…',
  abmColSerial: 'מספר סידורי',
  abmColModel: 'דגם',
  abmColFamily: 'משפחה',
  abmColOs: 'מערכת',
  abmColProfile: 'סטטוס פרופיל',
  abmColAssigned: 'שויך ב',
  abmProfileEmpty: 'ללא פרופיל',
  abmProfileAssigned: 'משויך',
  abmProfilePushed: 'נשלח',
  abmProfileRemoved: 'הוסר',
  abmRefreshAccount: 'רענון סטטוס',
  removeOverride: 'הסרה',

  mdmLead: 'סטטוס שרת MDM ואסימון ניהול.',
  mdmAdminToken: 'אסימון API',
  mdmSaveToken: 'שמירת אסימון',
  mdmAdminTokenHint:
    'לסקריפטים ו־curl אפשר עדיין לשלוח Authorization: Bearer. הכניסה לממשק היא עם Google.',
  apiDocsSettingsTitle: 'API ו־Webhooks',
  apiDocsSettingsLead: 'כל פעולות הניהול זמינות ב־REST. אירועים נשלחים לכתובות HTTPS עם חתימת HMAC.',
  apiDocsOpen: 'פתיחת מסמכי API',
  mdmAdminTokenMissing: 'אין הרשאת ניהול — התחברו מחדש.',
  mdmUseDefaultToken: 'שימוש בברירת מחדל',
  adminLoginTitle: 'כניסה לניהול',
  adminLoginLead: 'רק חשבונות שאושרו מראש יכולים להיכנס.',
  adminLoginGoogle: 'התחברות עם Google',
  adminLoginToken: 'כניסה עם אסימון',
  adminLoginTokenHint: 'Google לא הוגדר בשרת — אפשר להיכנס עם אסימון ADMIN_TOKENS (מקומי: dev-admin-token).',
  adminLoginNotAllowed: 'החשבון הזה לא מורשה לניהול.',
  adminLoginUnverified: 'צריך חשבון Google עם אימייל מאומת.',
  adminLoginFailed: 'ההתחברות נכשלה. נסו שוב.',
  adminLogout: 'יציאה',
  adminSignedInAs: 'מחוברים כ',
  mdmLive: 'פעיל',
  mdmStub: 'מצב stub',
  mdmDeviceInfo: 'פרטי מכשיר',
  mdmDeviceInfoTitle: 'תשובת מכשיר',
  mdmWaitingDevice: 'ממתין לתשובת המכשיר…',
  mdmNoDevices: 'אין מכשירים מנוהלים עדיין.',
  mdmEnrollHint: 'פרופיל הרשמה: /enroll',
  mdmAppsCount: '{n} אפליקציות',
  mdmProfilesCount: '{n} פרופילים',
  mdmAppVersion: 'גרסה',
  mdmBundleId: 'מזהה',
  mdmUpdateAvailable: 'יש עדכון',
  mdmShowRaw: 'XML גולמי',
  mdmLocation: 'מיקום',
  mdmOpenMaps: 'פתיחה במפות',
  mdmLocationNeedsLostMode:
    'איתור מיקום זמין רק כשהמכשיר במצב אבוד. הפעילו «מצב אבוד» ואז נסו שוב.',
  mdmCommandFailed: 'הפקודה נכשלה במכשיר.',

  status: 'סטטוס',
  type: 'סוג',
  all: 'הכול',
  pending: 'ממתין',
  approved: 'מאושר ברשימה',
  denied: 'נדחה',
  resolved: 'טופל',
  open: 'פתוח',
  closed: 'סגור',
  searchPlaceholder: 'חיפוש…',
  searchCount: '{shown} מתוך {total}',
  pickAllVisible: 'בחירת כל התוצאות',
  clearVisible: 'ניקוי התוצאות',
  pickFilterAll: 'הכול',
  pickFilterOn: 'נבחרו',
  pickFilterOff: 'לא נבחרו',
  pickFilterInGroup: 'בקבוצה',
  pickFilterOutGroup: 'לא בקבוצה',
  selectedDevices: 'נבחרו',
  membersHint: 'חפשו לפי כינוי או מספר סידורי, סמנו מכשירים, ושמרו.',
  membersUnsaved: 'יש שינויים שלא נשמרו',
  pickGroupFirst: 'בחרו קבוצה מהרשימה',
  groupDescPlaceholder: 'תיאור (אופציונלי)',
  saveGroup: 'שמירת פרטים',
  approve1h: 'אישור לשעה',
  approveForever: 'אישור קבוע',
  approveForeverHint: 'מוסיף לרשימת המותרים בלי תפוגה',
  moreOptions: 'עוד משכים',
  deny: 'דחייה',
  resolve: 'סגירה כטופל',
  resolveBug: 'סגירה כטופל',
  resolveGeneral: 'סגירה כטופל',
  denyGeneral: 'דחייה',
  grantScope: 'היקף האישור',
  thisDevice: 'מכשיר זה',
  aGroup: 'קבוצה',
  everyone: 'כולם',
  createGroup: 'קבוצה חדשה',
  groupName: 'שם',
  groupDesc: 'תיאור',
  members: 'חברים',
  saveMembers: 'שמירת חברים',
  viewAllow: 'מותרים',
  delete: 'מחיקה',
  noGroups: 'אין קבוצות עדיין.',
  addAllow: 'הוספת הרשאה',
  kind: 'סוג',
  scope: 'היקף',
  duration: 'משך',
  permanent: 'קבוע (בלי תפוגה)',
  hour: 'שעה',
  day: '24 שעות',
  minutes15: '15 דקות',
  today: 'היום',
  addToAllow: 'הוספה',
  global: 'כולם',
  group: 'קבוצה',
  deviceEffective: 'מכשיר',
  allSources: 'הכול',
  appsAndUrls: 'הכול',
  appsOnly: 'אפליקציות',
  urlsOnly: 'אתרים',
  loading: 'טוען…',
  emptyRequests: 'אין בקשות להצגה.',
  emptyAllow: 'אין פריטים ברשימה.',
  emptyDevices: 'אין מכשירים ידועים עדיין.',
  by: 'מאת',
  ok: 'בוצע',
  rename: 'שם',
  save: 'שמירה',
  revoke: 'הסרה',
  revokeConfirm: 'להסיר את ההרשאה?',
  nickname: 'כינוי',
  nicknameHint: 'שם ידידותי שמופיע בבקשות ובקבוצות.',
  memberCount: 'חברים',
  filterDevices: 'סינון…',
  credits: 'קרדיטים',
  creditBalance: 'יתרת קרדיטים',
  buyCredits: 'רכישת קרדיטים',
  buyCreditsTitle: 'רכישת קרדיטים',
  insufficientCredits: 'אין מספיק קרדיטים לבקשת גישה',
  insufficientCreditsHint: 'בקשת אפליקציה או אתר עולה קרדיטים. אפשר לרכוש חבילה או לבקש מהניהול.',
  companionCreditsHint: 'אין מספיק קרדיטים לבקשת גישה. פנו להנהלת בית הספר להוספת קרדיטים — רכישה באפליקציה אינה זמינה.',
  companionNoPurchase: 'רכישת קרדיטים מתבצעת מחוץ לאפליקציה או דרך הנהלת בית הספר.',
  accessCostsCredits: 'בקשת גישה עולה {n} קרדיט',
  packageCredits: '{n} קרדיטים',
  priceILS: '₪{n}',
  payNow: 'תשלום',
  paymentSuccess: 'התשלום התקבל — הקרדיטים נוספו',
  paymentCancelled: 'התשלום בוטל',
  paymentPending: 'ממתין לאישור תשלום…',
  giftCredits: 'הענקת קרדיטים',
  giftAmount: 'כמות',
  giftNote: 'הערה (אופציונלי)',
  giftOk: 'הקרדיטים נוספו למכשיר',
  adjustCredits: 'התאמת קרדיטים',
  adjustAmount: 'שינוי (+/−)',
  adjustAmountHint: 'מספר חיובי להוספה, שלילי להפחתה',
  adjustOk: 'היתרה עודכנה',
  lookupDevice: 'חיפוש מכשיר',
  currentBalance: 'יתרה נוכחית',
  recentLedger: 'יומן אחרון',
  ledgerEmpty: 'אין רשומות ביומן',
  ledgerReason: 'סיבה',
  ledgerDelta: 'שינוי',
  ledgerBalance: 'יתרה',
  ledgerNote: 'הערה',
  ledgerWhen: 'מתי',
  creditSettings: 'הגדרות קרדיטים',
  creditsSystemEnabled: 'מערכת קרדיטים פעילה',
  creditsSystemDisabledHint: 'כבוי: בקשות גישה בחינם, אין רכישה או יתרה בפורטל (מומלץ ל־App Review).',
  accessRequestCost: 'עלות בקשת גישה',
  accessRequestCostHint: 'כמה קרדיטים נגבים על כל בקשת אפליקציה או אתר',
  settingsSaved: 'ההגדרות נשמרו',
  creditPackagesAdmin: 'חבילות קרדיטים',
  creditPurchases: 'רכישות קרדיטים',
  creditPurchasesLead: 'מי רכש קרדיטים, כמה שילם, ומתי — כולל רכישות ממתינות.',
  creditPurchasesEmpty: 'אין רכישות להצגה',
  purchasePackage: 'חבילה',
  purchaseProvider: 'ספק',
  purchaseProviderNedarim: 'נדרים פלוס',
  purchaseProviderFake: 'סימולציה',
  purchaseStatusPaid: 'שולם',
  purchaseStatusPending: 'ממתין',
  purchaseStatusFailed: 'נכשל',
  purchaseStatusExpired: 'פג תוקף',
  newPackage: 'חבילה חדשה',
  editPackage: 'עריכת חבילה',
  packageName: 'שם בעברית',
  packageCreditsAmount: 'מספר קרדיטים',
  packagePriceILS: 'מחיר (₪)',
  packageSort: 'סדר הצגה',
  packageActive: 'פעילה',
  packageInactive: 'לא פעילה',
  deactivatePackage: 'השבתה',
  deactivatePackageConfirm: 'להשבית את החבילה? רכישות קיימות יישמרו.',
  packageSaved: 'החבילה נשמרה',
  goToCredits: 'ניהול קרדיטים',
  allotmentRules: 'הקצאות אוטומטיות',
  allotmentRulesHint:
    'הענקת קרדיטים תקופתיים שלא נערמים — בכל מחזור היתרה התקופתית מתאפסת לכמות שנקבעה',
  newAllotment: 'הקצאה חדשה',
  editAllotment: 'עריכת הקצאה',
  allotmentName: 'שם',
  allotmentAmount: 'כמות לכל מחזור',
  allotmentInterval: 'מרווח',
  allotmentIntervalDaily: 'יומי',
  allotmentIntervalWeekly: 'שבועי',
  allotmentIntervalMonthly: 'חודשי',
  allotmentTarget: 'יעד',
  allotmentTargetEveryone: 'כולם',
  allotmentTargetGroup: 'קבוצה',
  allotmentTargetIndividual: 'מכשיר בודד',
  allotmentEnabled: 'פעילה',
  allotmentDisabled: 'מושבתת',
  allotmentLastRun: 'ריצה אחרונה',
  allotmentNextPeriod: 'מחזור הבא',
  allotmentPeriodKey: 'מפתח מחזור',
  allotmentDeleteConfirm: 'למחוק את ההקצאה? קרדיטים תקופתיים שלא נוצלו יוחזרו.',
  allotmentSaved: 'ההקצאה נשמרה',
  allotmentDeleted: 'ההקצאה נמחקה',
  allotmentRunNow: 'הפעלה עכשיו',
  allotmentRunOk: 'ההקצאות הורצו',
  allotmentBalance: 'הקצאה תקופתית',
  permanentBalance: 'יתרה קבועה',
  availableBalance: 'זמין לשימוש',
  nedarimPay: 'תשלום בנדרים פלוס',
  paymentConfirming: 'מאשר תשלום…',
  choosePackage: 'בחרו חבילה',
  sourceEssential: 'חיוני',
  sourceGlobal: 'גלובלי',
  sourceGroup: 'קבוצה',
  sourceDevice: 'מכשיר',
  sourceGrant: 'זמני',
  sourcePack: 'חבילה',
  effectiveSearch: 'חיפוש אפליקציה, אתר, קבוצה או חבילה',
  effectiveDeviceBucket: 'רק המכשיר הזה',
  effectivePackOnDevice: 'חבילות על המכשיר',
  effectiveEveryone: 'לכולם',
  effectiveItemCount: '{n} פריטים',
  effectiveEmptySearch: 'אין התאמות לחיפוש',
  essentialNote: 'חיוני למערכת — לא ניתן להסיר',
  openGroup: 'ניהול',
  close: 'סגירה',
  details: 'פרטים על האפליקציה',
  hideDetails: 'הסתרת פרטים',
  showDetails: 'הצגת פרטים',
  loadingDetails: 'טוען פרטים מחנות האפליקציות…',
  appStoreLink: 'פתיחה ב-App Store',
  genre: 'קטגוריה',
  version: 'גרסה',
  rating: 'דירוג',
  contentRating: 'גיל',
  price: 'מחיר',
  size: 'גודל',
  released: 'יצא לאור',
  seller: 'מפיץ',
  bundleId: 'מזהה טכני',
  advancedInfo: 'מידע מתקדם',
  showMore: 'הצג עוד',
  showLess: 'הצג פחות',
  free: 'חינם',
  description: 'תיאור',
  screenshots: 'צילומי מסך',
  messages: 'הודעות',
  back: 'חזרה',
  /** Status copy depends on request type — use statusFor(). */
  statusLabel: {
    pending: 'ממתין לתשובה',
    approved: 'מאושר ברשימה',
    denied: 'נדחה',
    resolved: 'טופל',
  } as Record<string, string>,
  typeLabel: {
    access: 'גישה',
    general: 'כללי',
    bug: 'תקלה',
  } as Record<string, string>,
} as const

/** Human status for a ticket — access vs general/bug mean different things. */
export function statusFor(type: string, status: string): string {
  if (status === 'pending') return 'ממתין לתשובה'
  if (status === 'denied') return type === 'access' ? 'גישה נדחתה' : 'נדחה'
  if (status === 'resolved') {
    if (type === 'bug') return 'טופל / נסגר'
    return 'טופל'
  }
  if (status === 'approved') {
    if (type === 'access') return 'מאושר ברשימת המותרים'
    return 'טופל' // legacy general that used "approved"
  }
  return he.statusLabel[status] || status
}

export function statusClass(status: string): string {
  if (status === 'pending') return 'warn'
  if (status === 'denied') return 'bad'
  return 'ok'
}

/** What should happen next — for admin queue clarity. */
export function adminNextAction(type: string, status: string, lastAuthor?: string): { label: string; kind: 'act' | 'wait' | 'done' } {
  if (status !== 'pending') {
    return { label: statusFor(type, status), kind: 'done' }
  }
  if (lastAuthor === 'student' || !lastAuthor) {
    return { label: he.waitingYourReply, kind: 'act' }
  }
  return { label: he.waitingStudent, kind: 'wait' }
}

/** What the student should notice on the device portal. */
export function studentNextAction(type: string, status: string, lastAuthor?: string): { label: string; kind: 'act' | 'wait' | 'done' } {
  if (status !== 'pending') {
    return { label: statusFor(type, status), kind: 'done' }
  }
  if (lastAuthor === 'admin') {
    return { label: he.adminReplied, kind: 'act' }
  }
  return { label: he.waitingAdmin, kind: 'wait' }
}

