export const he = {
  brand: 'ניהול בית ספר',
  homeLead: 'יש לפתוח את הפורטל ממכשיר מנוהל, או להיכנס לממשק הניהול.',
  openAdmin: 'ממשק ניהול',
  portalTitle: 'בקשת עזרה',
  portalLead: 'בקשת אפליקציה או אתר, שאלה כללית, או דיווח על תקלה.',
  device: 'מכשיר',
  category: 'סוג הבקשה',
  catUrl: 'גישה לאתר',
  catApp: 'גישה לאפליקציה',
  catGeneral: 'בקשה כללית',
  catBug: 'דיווח תקלה',
  url: 'כתובת האתר',
  searchApp: 'חיפוש ב-App Store',
  search: 'חיפוש',
  searching: 'מחפש…',
  noApps: 'לא נמצאו אפליקציות.',
  pick: 'בחירה',
  selectedApp: 'אפליקציה שנבחרה',
  change: 'החלפה',
  subject: 'נושא',
  bugTitle: 'כותרת התקלה',
  reasonUrl: 'למה צריך את זה?',
  reasonApp: 'למה צריך את האפליקציה?',
  reasonBug: 'מה קרה? (שלבי שחזור)',
  reasonGeneral: 'פרטים',
  submit: 'שליחה',
  sending: 'שולח…',
  alreadyAllowed: 'כבר מאושר במכשיר',
  pendingRequest: 'יש כבר בקשה ממתינה',
  deniedBefore: 'נדחה בעבר — אפשר לבקש שוב',
  checkStatus: 'בודק הרשאות…',
  myRequests: 'הבקשות שלי',
  noRequests: 'אין בקשות עדיין.',
  admin: 'ניהול',
  adminLead: 'בקשות, קבוצות מכשירים ורשימות מותרים.',
  tabRequests: 'בקשות',
  tabGroups: 'קבוצות',
  tabAllow: 'רשימות מותרים',
  status: 'סטטוס',
  type: 'סוג',
  all: 'הכול',
  pending: 'ממתין',
  approved: 'אושר',
  denied: 'נדחה',
  resolved: 'טופל',
  open: 'פתוח',
  closed: 'סגור',
  sort: 'מיון',
  newest: 'החדש קודם',
  oldest: 'הישן קודם',
  searchPlaceholder: 'חיפוש…',
  approve1h: 'אישור לשעה',
  approveForever: 'אישור קבוע',
  deny: 'דחייה',
  resolve: 'סמן כטופל',
  grantScope: 'היקף האישור',
  thisDevice: 'המכשיר הזה',
  aGroup: 'קבוצה',
  everyone: 'כולם',
  createGroup: 'יצירת קבוצה',
  groupName: 'שם',
  groupDesc: 'תיאור (אופציונלי)',
  members: 'חברים',
  saveMembers: 'שמירת חברים',
  viewAllow: 'רשימת מותרים',
  delete: 'מחיקה',
  noGroups: 'אין קבוצות — יצירה למעלה.',
  addAllow: 'הוספת הרשאה',
  kind: 'סוג',
  scope: 'היקף',
  duration: 'משך',
  permanent: 'קבוע',
  hour: 'שעה',
  day: '24 שעות',
  minutes15: '15 דקות',
  today: 'עד סוף היום',
  addToAllow: 'הוספה לרשימה',
  global: 'כולם (גלובלי)',
  group: 'קבוצה',
  deviceEffective: 'מכשיר (אפקטיבי)',
  allSources: 'כל המקורות',
  appsAndUrls: 'אפליקציות ואתרים',
  appsOnly: 'אפליקציות בלבד',
  urlsOnly: 'אתרים בלבד',
  token: 'אסימון ניהול',
  saveToken: 'שמירה',
  loading: 'טוען…',
  emptyRequests: 'אין בקשות התואמות לסינון.',
  emptyAllow: 'אין פריטים התואמים לסינון.',
  created: 'נוצר',
  expires: 'פג תוקף',
  by: 'מאת',
  error: 'שגיאה',
  ok: 'בוצע',
  statusLabel: {
    pending: 'ממתין',
    approved: 'אושר',
    denied: 'נדחה',
    resolved: 'טופל',
  } as Record<string, string>,
  typeLabel: {
    access: 'גישה',
    general: 'כללי',
    bug: 'תקלה',
  } as Record<string, string>,
} as const

export type HeKey = keyof typeof he
