export const he = {
  brand: 'ניהול בית ספר',
  homeLead: 'יש לפתוח את הפורטל ממכשיר מנוהל, או להיכנס לממשק הניהול.',
  openAdmin: 'ממשק ניהול',
  portalTitle: 'בקשת עזרה',
  portalLead: 'בקשת אפליקציה או אתר, שאלה כללית, או דיווח על תקלה — אפשר גם להמשיך לשוחח עם הניהול.',
  device: 'מכשיר',
  category: 'סוג הבקשה',
  catUrl: 'אתר',
  catApp: 'אפליקציה',
  catGeneral: 'כללי',
  catBug: 'תקלה',
  url: 'כתובת האתר',
  urlWillSave: 'יישמר כ',
  searchApp: 'חיפוש ב-App Store',
  search: 'חיפוש',
  searching: 'מחפש…',
  noApps: 'לא נמצאו אפליקציות.',
  pick: 'בחירה',
  selectedApp: 'אפליקציה שנבחרה',
  change: 'החלפה',
  subject: 'נושא',
  bugTitle: 'כותרת התקלה',
  reasonUrl: 'למה צריך את זה?',
  reasonApp: 'למה צריך את האפליקציה?',
  reasonBug: 'מה קרה? (שלבי שחזור)',
  reasonGeneral: 'פרטים',
  submit: 'שליחה',
  sending: 'שולח…',
  alreadyAllowed: 'כבר ברשימת המותרים',
  alreadyAllowedHint: 'כבר מאושר במכשיר — אין צורך לבקש שוב.',
  pendingRequest: 'בקשה פתוחה',
  deniedBefore: 'נדחה בעבר — אפשר לבקש שוב',
  checkStatus: 'בודק הרשאות…',
  myRequests: 'הבקשות שלי',
  noRequests: 'עדיין אין בקשות.',
  sentOk: 'הבקשה נשלחה',
  openThread: 'פתיחת שיחה',
  conversation: 'שיחה',
  reply: 'תשובה',
  replyPlaceholder: 'כתבו תשובה…',
  replyPlaceholderAdmin: 'הוסיפו הערה לתלמיד…',
  sendReply: 'שליחה',
  pickRequest: 'בחרו בקשה מהרשימה',
  lastMsg: 'אחרון',
  queue: 'תור בקשות',
  ticket: 'בקשה נבחרת',
  you: 'אתם',
  adminRole: 'ניהול',
  studentRole: 'תלמיד',
  noMessages: 'אין הודעות עדיין.',
  reopenHint: 'תשובה שלכם תפתח מחדש את הבקשה אצל הניהול.',
  adminReplied: 'תשובה מהניהול',
  waitingYourReply: 'צריך תשובה',
  waitingStudent: 'ממתין לתלמיד',
  waitingAdmin: 'ממתין לניהול',
  closedTicket: 'סגור',
  nextAction: 'מצב',
  lastFromAdmin: 'מהניהול',
  lastFromYou: 'מאתכם',
  lastFromStudent: 'מהתלמיד',
  admin: 'ניהול',
  adminLead: 'בקשות, שיחות ורשימות מותרים.',
  tabRequests: 'בקשות',
  tabGroups: 'קבוצות',
  tabAllow: 'מותרים',
  tabDevices: 'מכשירים',
  tabCredits: 'קרדיטים',
  status: 'סטטוס',
  type: 'סוג',
  all: 'הכול',
  pending: 'ממתין',
  approved: 'מאושר ברשימה',
  denied: 'נדחה',
  resolved: 'טופל',
  open: 'פתוח',
  closed: 'סגור',
  searchPlaceholder: 'חיפוש…',
  approve1h: 'אישור לשעה',
  approveForever: 'אישור קבוע',
  approveForeverHint: 'מוסיף לרשימת המותרים בלי תפוגה',
  moreOptions: 'עוד משכים',
  deny: 'דחייה',
  resolve: 'סגירה כטופל',
  resolveBug: 'סגירה כטופל',
  resolveGeneral: 'סגירה כטופל',
  denyGeneral: 'דחייה',
  grantScope: 'היקף האישור',
  thisDevice: 'מכשיר זה',
  aGroup: 'קבוצה',
  everyone: 'כולם',
  createGroup: 'קבוצה חדשה',
  groupName: 'שם',
  groupDesc: 'תיאור',
  members: 'חברים',
  saveMembers: 'שמירת חברים',
  viewAllow: 'מותרים',
  delete: 'מחיקה',
  noGroups: 'אין קבוצות עדיין.',
  addAllow: 'הוספת הרשאה',
  kind: 'סוג',
  scope: 'היקף',
  duration: 'משך',
  permanent: 'קבוע (בלי תפוגה)',
  hour: 'שעה',
  day: '24 שעות',
  minutes15: '15 דקות',
  today: 'היום',
  addToAllow: 'הוספה',
  global: 'כולם',
  group: 'קבוצה',
  deviceEffective: 'מכשיר',
  allSources: 'הכול',
  appsAndUrls: 'הכול',
  appsOnly: 'אפליקציות',
  urlsOnly: 'אתרים',
  loading: 'טוען…',
  emptyRequests: 'אין בקשות להצגה.',
  emptyAllow: 'אין פריטים ברשימה.',
  emptyDevices: 'אין מכשירים ידועים עדיין.',
  by: 'מאת',
  ok: 'בוצע',
  rename: 'שם',
  save: 'שמירה',
  revoke: 'הסרה',
  revokeConfirm: 'להסיר את ההרשאה?',
  nickname: 'כינויי מכשירים',
  nicknameHint: 'שם ידידותי שמופיע בבקשות ובקבוצות.',
  memberCount: 'חברים',
  filterDevices: 'סינון…',
  credits: 'קרדיטים',
  creditBalance: 'יתרת קרדיטים',
  buyCredits: 'רכישת קרדיטים',
  buyCreditsTitle: 'רכישת קרדיטים',
  insufficientCredits: 'אין מספיק קרדיטים לבקשת גישה',
  insufficientCreditsHint: 'בקשת אפליקציה או אתר עולה קרדיטים. אפשר לרכוש חבילה או לבקש מהניהול.',
  accessCostsCredits: 'בקשת גישה עולה {n} קרדיט',
  packageCredits: '{n} קרדיטים',
  priceILS: '₪{n}',
  payNow: 'תשלום',
  paymentSuccess: 'התשלום התקבל — הקרדיטים נוספו',
  paymentCancelled: 'התשלום בוטל',
  paymentPending: 'ממתין לאישור תשלום…',
  giftCredits: 'הענקת קרדיטים',
  giftAmount: 'כמות',
  giftNote: 'הערה (אופציונלי)',
  giftOk: 'הקרדיטים נוספו למכשיר',
  adjustCredits: 'התאמת קרדיטים',
  adjustAmount: 'שינוי (+/−)',
  adjustAmountHint: 'מספר חיובי להוספה, שלילי להפחתה',
  adjustOk: 'היתרה עודכנה',
  lookupDevice: 'חיפוש מכשיר',
  currentBalance: 'יתרה נוכחית',
  recentLedger: 'יומן אחרון',
  ledgerEmpty: 'אין רשומות ביומן',
  ledgerReason: 'סיבה',
  ledgerDelta: 'שינוי',
  ledgerBalance: 'יתרה',
  ledgerNote: 'הערה',
  ledgerWhen: 'מתי',
  creditSettings: 'הגדרות קרדיטים',
  accessRequestCost: 'עלות בקשת גישה',
  accessRequestCostHint: 'כמה קרדיטים נגבים על כל בקשת אפליקציה או אתר',
  settingsSaved: 'ההגדרות נשמרו',
  creditPackagesAdmin: 'חבילות קרדיטים',
  newPackage: 'חבילה חדשה',
  editPackage: 'עריכת חבילה',
  packageName: 'שם בעברית',
  packageCreditsAmount: 'מספר קרדיטים',
  packagePriceILS: 'מחיר (₪)',
  packageSort: 'סדר הצגה',
  packageActive: 'פעילה',
  packageInactive: 'לא פעילה',
  deactivatePackage: 'השבתה',
  deactivatePackageConfirm: 'להשבית את החבילה? רכישות קיימות יישמרו.',
  packageSaved: 'החבילה נשמרה',
  goToCredits: 'ניהול קרדיטים',
  allotmentRules: 'הקצאות אוטומטיות',
  allotmentRulesHint:
    'הענקת קרדיטים תקופתיים שלא נערמים — בכל מחזור היתרה התקופתית מתאפסת לכמות שנקבעה',
  newAllotment: 'הקצאה חדשה',
  editAllotment: 'עריכת הקצאה',
  allotmentName: 'שם',
  allotmentAmount: 'כמות לכל מחזור',
  allotmentInterval: 'מרווח',
  allotmentIntervalDaily: 'יומי',
  allotmentIntervalWeekly: 'שבועי',
  allotmentIntervalMonthly: 'חודשי',
  allotmentTarget: 'יעד',
  allotmentTargetEveryone: 'כולם',
  allotmentTargetGroup: 'קבוצה',
  allotmentTargetIndividual: 'מכשיר בודד',
  allotmentEnabled: 'פעילה',
  allotmentDisabled: 'מושבתת',
  allotmentLastRun: 'ריצה אחרונה',
  allotmentNextPeriod: 'מחזור הבא',
  allotmentPeriodKey: 'מפתח מחזור',
  allotmentDeleteConfirm: 'למחוק את ההקצאה? קרדיטים תקופתיים שלא נוצלו יוחזרו.',
  allotmentSaved: 'ההקצאה נשמרה',
  allotmentDeleted: 'ההקצאה נמחקה',
  allotmentRunNow: 'הפעלה עכשיו',
  allotmentRunOk: 'ההקצאות הורצו',
  allotmentBalance: 'הקצאה תקופתית',
  permanentBalance: 'יתרה קבועה',
  availableBalance: 'זמין לשימוש',
  fakeNedarim: 'סימולציית נדרים פלוס',
  choosePackage: 'בחרו חבילה',
  sourceEssential: 'חיוני',
  sourceGlobal: 'גלובלי',
  sourceGroup: 'קבוצה',
  sourceDevice: 'מכשיר',
  sourceGrant: 'זמני',
  essentialNote: 'חיוני למערכת — לא ניתן להסיר',
  openGroup: 'ניהול',
  close: 'סגירה',
  details: 'פרטים על האפליקציה',
  hideDetails: 'הסתרת פרטים',
  showDetails: 'הצגת פרטים',
  loadingDetails: 'טוען פרטים מחנות האפליקציות…',
  appStoreLink: 'פתיחה ב-App Store',
  genre: 'קטגוריה',
  version: 'גרסה',
  rating: 'דירוג',
  contentRating: 'גיל',
  price: 'מחיר',
  size: 'גודל',
  released: 'יצא לאור',
  seller: 'מפיץ',
  bundleId: 'מזהה טכני',
  advancedInfo: 'מידע מתקדם',
  showMore: 'הצג עוד',
  showLess: 'הצג פחות',
  free: 'חינם',
  description: 'תיאור',
  screenshots: 'צילומי מסך',
  messages: 'הודעות',
  back: 'חזרה',
  /** Status copy depends on request type — use statusFor(). */
  statusLabel: {
    pending: 'ממתין לתשובה',
    approved: 'מאושר ברשימה',
    denied: 'נדחה',
    resolved: 'טופל',
  } as Record<string, string>,
  typeLabel: {
    access: 'גישה',
    general: 'כללי',
    bug: 'תקלה',
  } as Record<string, string>,
} as const

/** Human status for a ticket — access vs general/bug mean different things. */
export function statusFor(type: string, status: string): string {
  if (status === 'pending') return 'ממתין לתשובה'
  if (status === 'denied') return type === 'access' ? 'גישה נדחתה' : 'נדחה'
  if (status === 'resolved') {
    if (type === 'bug') return 'טופל / נסגר'
    return 'טופל'
  }
  if (status === 'approved') {
    if (type === 'access') return 'מאושר ברשימת המותרים'
    return 'טופל' // legacy general that used "approved"
  }
  return he.statusLabel[status] || status
}

export function statusClass(status: string): string {
  if (status === 'pending') return 'warn'
  if (status === 'denied') return 'bad'
  return 'ok'
}

/** What should happen next — for admin queue clarity. */
export function adminNextAction(type: string, status: string, lastAuthor?: string): { label: string; kind: 'act' | 'wait' | 'done' } {
  if (status !== 'pending') {
    return { label: statusFor(type, status), kind: 'done' }
  }
  if (lastAuthor === 'student' || !lastAuthor) {
    return { label: he.waitingYourReply, kind: 'act' }
  }
  return { label: he.waitingStudent, kind: 'wait' }
}

/** What the student should notice on the device portal. */
export function studentNextAction(type: string, status: string, lastAuthor?: string): { label: string; kind: 'act' | 'wait' | 'done' } {
  if (status !== 'pending') {
    return { label: statusFor(type, status), kind: 'done' }
  }
  if (lastAuthor === 'admin') {
    return { label: he.adminReplied, kind: 'act' }
  }
  return { label: he.waitingAdmin, kind: 'wait' }
}

